### ISSUE TITLE
Holding key makes a plus character appears

### ISSUE THREAD

**Issue by Underzzoo** [probil/v-mask#29] opened 2017-03-30 22:41 UTC
Please, in the same [exemple](https://cdn.rawgit.com/probil/v-mask/vue-2.0/demo/index.html), if you hold a character and change the focus with tab, and hit another character, a misterious character appears breaking the mask.

Thanks

**Comment by probil** [comment] 2017-04-02 07:26
It seems like it's duplicate of #16#issuecomment-279682010

**Closed** 2017-04-03 17:23 UTC
Labels: duplicate
