### ISSUE TITLE
[nuxt.js] [FF] Not working on FireFox 45.0.2 (and later)

### ISSUE THREAD

**Issue by koddr** [probil/v-mask#19] opened 2017-02-08 08:44 UTC
Hello. I use your awesome plugin with Nuxt.js project and see simple blink mask after input any symbols.

If I watch on Safari (os x 10.11) or Opera/Chrome — all WebKit browsers working fine with v-mask plugin.

How to fix it?

**Comment by probil** [comment] 2017-02-13 00:47
I can't reproduce it on my machine (Firefox 51 / Firefox DevEdition 53, Archlinux)
Can you check the last version of the lib? Maybe it's already fixed

**Comment by koddr** [comment] 2017-02-13 17:43
Thank for response.

I try v-mask on FireFox 49.0.1 (OS X 10.11) and nothing change. Now, I update FF to latest version (51.0.1 x64) but v-mask don't work. This is my site https://gderemonta.net/ (form on the middle page, second field with v-mask "+7 (###) ###-##-##"). Maybe you check on your computer?

**Comment by probil** [comment] 2017-02-13 22:00
Reproduced on my machine on with FF51 / FF DE 53 (but works on the latest Chrome). I will try to find out why it doesn't work. Thanks for the issue.

**Comment by iFgR** [comment] 2017-03-09 22:49
I solved my problem with FF and Backspace at #26

**Comment by sidbenac** [comment] 2017-03-23 20:23
doesn't work on IE 11, do you know if there's a workaround this ?

**Comment by probil** [comment] 2017-03-23 23:11
@sidbenac Should be fixed in #26 . I have planed to review and merge it on this weekend

**Closed** 2017-04-25 21:34 UTC
Labels: bug, help wanted, intend to implement

**Comment by probil** [comment] 2017-04-25 21:36
Please, check it out. It works fine in `v1.1.0` and up

**Comment by koddr** [comment] 2017-04-26 07:39
@probil thanks a lot! ;)
