### ISSUE TITLE
Caret issue on mobile chrome leading to incorrect input

### ISSUE THREAD

**Issue by paraboul** [probil/v-mask#61] opened 2017-10-08 20:55 UTC
Trying a simple mask (##/##) on mobile chrome.

The caret positions itself before the '/' and stays one char behind (entering 1234 actually displays 12/43)

**Comment by jontybrook** [comment] 2017-10-11 00:16
I'm also seeing this. Using v-mask="'£######'", all works fine on desktop but in Chrome on mobile the first character flips infront of the subsequent chars. Eg entering "1234" results in "2341".

**Comment by shrpne** [comment] 2017-10-18 09:11
Looks like only Samsung devices affected by this issue. I have tested with Galaxy s5 mini.
Other devices with chrome works fine for me

**Comment by paraboul** [comment] 2017-10-18 09:13
@shrpne this is related to the Chrome version. Currently testing on an updated chrome on Android O (e.g. Google pixel)

**Comment by luiztsmelo** [comment] 2017-10-23 21:04
Same here, using a xiaomi device and chrome 61

**Comment by tonpereira** [comment] 2017-12-15 17:26
Hello, I'm having the same problem on Chrome mobile, and on Android 8 ..
Has any solution been found for this bug?
a field with mascara 000.000.000 and in time to appear the "." the mouse cursor goes to before the next digit, after the ".".

**Comment by probil** [comment] 2018-01-31 15:28
Seems like related to #41

**Comment by lndsy-cherry** [comment] 2018-02-13 18:18
I'm experiencing this issue as well. According to issue 41, it looks like this has been going on for a while. Any updates @probil? V-mask has worked so well up until this point!

**Comment by probil** [comment] 2018-02-13 19:02
@lndsy-cherry I will try to reproduce and fix today (in an hour)

**Comment by probil** [comment] 2018-02-13 23:09
@lndsy-cherry I can't reproduce it on my android phone. :(
Could you please check the fix on your device? It's not yet published on npm so you need to install `v-mask` this way:
```
npm i probil/v-mask#feature/fix-caret-on-mobile-chrome
```
Please, let me know about the result of the testing.

**Comment by lndsy-cherry** [comment] 2018-02-14 18:11
@probil I just tested and that fix worked like a charm! Please merge and thank you so much again for this! :)

**Comment by probil** [comment] 2018-02-14 20:19
Fixed in `v1.3.2`. Thanks everyone.

**Closed by probil** 2018-02-14 20:19 UTC
Labels: bug, help wanted

**Comment by lndsy-cherry** [comment] 2018-02-27 20:12
@probil it looks like some Android+Chrome devices are still experiencing an issue (I was testing on a Galaxy S5 earlier and noticed some cursor movement when typing a simple mask like ###-###), though it seems like there is no issue on an emulated Android+Chrome experience.

I see in your code you're using initEvent in the trigger function, yet this looks to be a deprecated feature (https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent). I'm wondering if this may be affecting this. Would you have any plans to update the event triggering used?

**Comment by probil** [comment] 2018-02-27 21:49
@lndsy-cherry
Let's discuss in the separate issue. Could you please create it?
